# -*- coding: utf-8 -*-
"""FASE4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DKXH6OSIvFmYSLcfuTAAfzziY9WOnd_S

# 1. Importando Bibliotecas
Primeiramente, vamos importar as bibliotecas necessárias para nossa análise.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#!pip install streamlit
import streamlit as st

import yfinance as yf

st.set_page_config(
    page_title="Painel da B3",
    layout="wide",
)

st.header("**PAINEL DE PREÇOS E DIVIDENDOS DA BOLSA DE VALORES**")

ticker = st.text_input("Digite o ticker da ação:", "PETR4")
empresa = yf.Ticker(f"{ticker}.SA")

tickerDF = empresa.history(
    start="2026-06-01",
    end="2026-06-30"
)

col1, col2, col3 = st.columns(3)
with col1:
    st.write(f"**Empresa** {empresa.info['longName']}")
with col2:
    st.write(f"**Setor** {empresa.info['sector']}")
with col3:
    st.write(f"**Preço Atual** {empresa.info['currentPrice']}")

st.line_chart(tickerDF['Close'])



"""# 2. Carregando o Conjunto de Dados
Usaremos o conjunto de dados "Obesity.csv", que contém características de pessoas com diversos níveis de obesidade ou não.

"""

from google.colab import files

# upload
arquivos = files.upload()

# carregar
obesity = pd.read_csv('Obesity.csv', sep=',')

# criar classificação
X = obesity.drop('Obesity', axis=1)
y = obesity['Obesity']

#wine = datasets.load_wine()
#X = wine.data
#y = wine.target

"""# 3. Análise Exploratória de Dados
Vamos dar uma olhada nas primeiras linhas do conjunto de dados e entender suas características.
"""

#df = pd.DataFrame(X, columns=wine.feature_names)
#df['target'] = y
df = pd.read_csv('Obesity.csv', sep=',')
df.head()

X.head()

y.head()

"""# 4. Pré-processamento de Dados
Dividimos os dados em conjuntos de treinamento e teste.
"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=123)

"""Normalizamos os dados para melhorar o desempenho de alguns algoritmos.


"""

from sklearn.preprocessing import StandardScaler

# Identify categorical columns
categorical_cols = X_train.select_dtypes(include=['object', 'category']).columns

# Apply one-hot encoding to training and test sets
X_train_encoded = pd.get_dummies(X_train, columns=categorical_cols, drop_first=True)
X_test_encoded = pd.get_dummies(X_test, columns=categorical_cols, drop_first=True)

# Align columns - this is crucial if one-hot encoding results in different columns
# (e.g., if one set doesn't have all categories present in the other)
X_train_encoded, X_test_encoded = X_train_encoded.align(X_test_encoded, join='left', axis=1, fill_value=0)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train_encoded)
X_test = scaler.transform(X_test_encoded)

X_train

"""# 5. Modelos de Aprendizado Supervisionado
5.1. K-Nearest Neighbors (KNN)
"""

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)

y_pred_knn

"""5.2. Regressão Logística

"""

from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train, y_train)
y_pred_logreg = logreg.predict(X_test)

"""5.3. Árvores de Decisão

"""

from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier()
tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)

"""5.4. Random Forest

"""

from sklearn.ensemble import RandomForestClassifier

forest = RandomForestClassifier(n_estimators=100)
forest.fit(X_train, y_train)
y_pred_forest = forest.predict(X_test)

"""5.5. Support Vector Machine (SVM)

"""

from sklearn.svm import SVC

svm = SVC()
svm.fit(X_train, y_train)
y_pred_svm = svm.predict(X_test)

"""# 6. Avaliação dos Modelos
Criamos uma função para avaliar os modelos de forma consistente.
"""

def avaliar_modelo(y_test, y_pred, nome_modelo):
    print(f"Resultados para {nome_modelo}:")
    print("Acurácia:", accuracy_score(y_test, y_pred))
    print("Matriz de Confusão:\n", confusion_matrix(y_test, y_pred))
    print("Relatório de Classificação:\n", classification_report(y_test, y_pred))
    print("-" * 60)

"""Avaliação de cada modelo:


"""

avaliar_modelo(y_test, y_pred_knn, "K-Nearest Neighbors")
avaliar_modelo(y_test, y_pred_logreg, "Regressão Logística")
avaliar_modelo(y_test, y_pred_tree, "Árvore de Decisão")
avaliar_modelo(y_test, y_pred_forest, "Random Forest")
avaliar_modelo(y_test, y_pred_svm, "Support Vector Machine")

"""# 7. Conclusão
Comparamos vários modelos de classificação e observamos suas performances no conjunto de dados de vinhos. Cada modelo tem suas vantagens e pode ser mais adequado dependendo do contexto.

# 8. Exercícios
Agora é a sua vez! Realize as seguintes atividades e observe os resultados:

1. Altere o tamanho do conjunto de teste: Modifique o parâmetro test_size para 0.2 na função train_test_split e reavalie os modelos. Como isso afeta a acurácia?

2. Experimente diferentes valores de k no KNN: Altere o valor de n_neighbors para 3 e 7 no modelo KNN. Qual valor produz a melhor acurácia?

3. Remova a normalização dos dados: Comente ou remova as linhas onde aplicamos o StandardScaler e treine os modelos novamente. Quais modelos são mais afetados?

4. Ajuste a profundidade máxima da Árvore de Decisão: Defina o parâmetro max_depth=3 no DecisionTreeClassifier. Isso melhora ou piora o desempenho?

5. Use um kernel diferente no SVM: Altere o parâmetro kernel para 'linear' no modelo SVM. Compare os resultados com o kernel padrão.
"""

