# -*- coding: utf-8 -*-
"""testeMFMK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zAeL7ZQYYAENboMNQ6w3HwQy-RYAz3-A
"""

#!pip install streamlit

import streamlit as st
import pandas as pd

dados = pd.read_csv('https://raw.githubusercontent.com/MonicaFMK/FIAP-Fase4/refs/heads/main/Obesity-formatado-LIMPO.csv')

st.write('# DADOS OBESITY')

st.write('### Gênero')
input_genero = st.selectbox('Qual o gênero?',dados['Gender'].unique())

st.write('### Idade')
input_idade = float(st.slider('Selecione a idade',14,100))

st.write('### Altura')
input_altura = float(st.number_input('Digite a altura e pressione ENTER para confirmar',0))

st.write('### Peso')
input_peso = float(st.number_input('Digite o peso e pressione ENTER para confirmar',0))

st.write('### Histórico familiar')
input_historico_familiar = st.radio('Possui histórico familiar?', ['Sim','Não'])
input_historico_familiar_dict = {'Sim':'yes','Não':'no'}
input_historico_familiar = input_historico_familiar_dict.get(input_historico_familiar)

st.write('### Alimentos muito calóricos')
input_consumo_calorico = st.radio('Consumo frequente de alimentos muito calóricos?', ['Sim','Não'])
input_consumo_calorico_dict = {'Sim':'yes','Não':'no'}
input_consumo_calorico = input_consumo_calorico_dict.get(input_consumo_calorico)

st.write('### Vegetais nas refeições')
input_consumo_vegetais = st.radio('Frequência de consumo de vegetais nas refeições', ['1 - raramente','2 - às vezes','3 - sempre'])
input_consumo_vegetais_dict = {'1 - raramente':1,'2 - às vezes':2,'3 - sempre':3}
input_consumo_vegetais = input_consumo_vegetais_dict.get(input_consumo_vegetais)

st.write('### Refeições')
input_refeicoes = st.radio('Número de refeições principais por dia', [1,2,3,4])

st.write('### Lanches')
input_Lanches = st.radio('Consumo de lanches/comes entre as refeições', ['não consome','às vezes','frequentemente','sempre'])
input_consumo_Lanches_dict = {'não consome':'no','às vezes':'Sometimes','frequentemente':'Frequently','sempre':'Always'}
input_consumo_Lanches = input_consumo_Lanches_dict.get(input_Lanches)

st.write('### Smoke')
input_Smoke = st.radio('Hábito de fumar?', ['Sim','Não'])
input_Smoke_dict = {'Sim':'yes','Não':'no'}
input_Smoke = input_Smoke_dict.get(input_Smoke)

st.write('### Água')
input_agua = st.radio('Consumo diário de água (L/dia).', [1,2,3])

st.write('### Ingestão calórica')
input_calorica = st.radio('Monitora a ingestão calórica diária?', ['Sim','Não'])
input_calorica_dict = {'Sim':'yes','Não':'no'}
input_calorica = input_calorica_dict.get(input_calorica)

st.write('### Atividade física')
input_atividade = st.radio('Frequência semanal de atividade física', ['nenhuma','1–2×/sem','3–4×/sem',' 5×/sem ou mais'])
input_atividade_dict = {'nenhuma':0,'1–2×/sem':1,'3–4×/sem':2,'5×/sem ou mais':3}
input_atividade = input_atividade_dict.get(input_atividade)

st.write('### Eletrônicos')
input_tempo_eletronico = st.radio('Tempo diário usando dispositivos eletrônicos', ['0–2 h/dia','3–5 h/dia','> 5 h/dia'])
input_tempo_eletronico_dict = {'0–2 h/dia':0,'3–5 h/dia':1,'> 5 h/dia':2}
input_tempo_eletronico = input_tempo_eletronico_dict.get(input_tempo_eletronico)

st.write('### Bebidas alcólicas')
input_Bebidas = st.radio('Consumo de bebida alcoólica', ['não bebe','às vezes','frequentemente','sempre'])
input_Bebidas_dict = {'não bebe':'no','às vezes':'Sometimes','frequentemente':'Frequently','sempre':'Always'}
input_Bebidas = input_Bebidas_dict.get(input_Bebidas)

st.write('### Meio de transporte')
input_transporte = st.radio('Meio de transporte habitual', ['carro','moto','bicicleta','transporte público','a pé'])
input_transporte_dict = {'carro':'Automobile','moto':'Motorbike','bicicleta':'Bike','transporte público':'Public_Transportation','a pé':'Walking'}
input_transporte = input_transporte_dict.get(input_transporte)

novo_dado = [
    input_genero,
    input_idade,
    input_altura,
    input_peso,
    input_historico_familiar,
    input_consumo_calorico,
    input_consumo_vegetais,
    input_refeicoes,
    input_consumo_Lanches,
    input_Smoke,
    input_agua,
    input_calorica,
    input_atividade,
    input_tempo_eletronico,
    input_Bebidas,
    input_transporte
]