# -*- coding: utf-8 -*-
"""testeMFMK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zAeL7ZQYYAENboMNQ6w3HwQy-RYAz3-A
"""

#!pip install streamlit

import streamlit as st

st.write('*Dados obesity')