# -*- coding: utf-8 -*-
"""testeMFMK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zAeL7ZQYYAENboMNQ6w3HwQy-RYAz3-A
"""

#!pip install streamlit

import streamlit as st
import pandas as pd

dados = pd.read_csv('https://raw.githubusercontent.com/MonicaFMK/FIAP-Fase4/refs/heads/main/Obesity.csv')

st.write('# DADOS OBESITY')

st.write('### Idade')
input_idade = float(st.slider('Selecione a idade',14,100))

st.write('### Gênero')
input_genero = st.selectbox('Qual o gênero?',dados['Gender'].unique())